// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator_change.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This is used to prove validator changes.
type ValidatorChangeProof struct {
	// A list of LedgerInfos with contiguous increasing epoch numbers.
	LedgerInfoWithSigs []*LedgerInfoWithSignatures `protobuf:"bytes,1,rep,name=ledger_info_with_sigs,json=ledgerInfoWithSigs,proto3" json:"ledger_info_with_sigs,omitempty"`
	// A flag (when true) that indicates the above list is incomplete and only
	// contains the first N epoch changes.
	More                 bool     `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorChangeProof) Reset()         { *m = ValidatorChangeProof{} }
func (m *ValidatorChangeProof) String() string { return proto.CompactTextString(m) }
func (*ValidatorChangeProof) ProtoMessage()    {}
func (*ValidatorChangeProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_484a7446a4b3dd15, []int{0}
}

func (m *ValidatorChangeProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorChangeProof.Unmarshal(m, b)
}
func (m *ValidatorChangeProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorChangeProof.Marshal(b, m, deterministic)
}
func (m *ValidatorChangeProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorChangeProof.Merge(m, src)
}
func (m *ValidatorChangeProof) XXX_Size() int {
	return xxx_messageInfo_ValidatorChangeProof.Size(m)
}
func (m *ValidatorChangeProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorChangeProof.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorChangeProof proto.InternalMessageInfo

func (m *ValidatorChangeProof) GetLedgerInfoWithSigs() []*LedgerInfoWithSignatures {
	if m != nil {
		return m.LedgerInfoWithSigs
	}
	return nil
}

func (m *ValidatorChangeProof) GetMore() bool {
	if m != nil {
		return m.More
	}
	return false
}

func init() {
	proto.RegisterType((*ValidatorChangeProof)(nil), "types.ValidatorChangeProof")
}

func init() {
	proto.RegisterFile("validator_change.proto", fileDescriptor_484a7446a4b3dd15)
}

var fileDescriptor_484a7446a4b3dd15 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0x8a, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0x12, 0xcc, 0x49, 0x4d, 0x49, 0x4f,
	0x2d, 0x8a, 0xcf, 0xcc, 0x4b, 0xcb, 0x87, 0xc8, 0x28, 0xd5, 0x71, 0x89, 0x84, 0xc1, 0xf4, 0x38,
	0x83, 0xb5, 0x04, 0x14, 0xe5, 0xe7, 0xa7, 0x09, 0x05, 0x71, 0x89, 0x22, 0x29, 0x8e, 0x2f, 0xcf,
	0x2c, 0xc9, 0x88, 0x2f, 0xce, 0x4c, 0x2f, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd7,
	0x03, 0x9b, 0xa8, 0xe7, 0x03, 0x56, 0xe3, 0x99, 0x97, 0x96, 0x1f, 0x9e, 0x59, 0x92, 0x11, 0x9c,
	0x99, 0x9e, 0x97, 0x58, 0x52, 0x5a, 0x94, 0x5a, 0x1c, 0x24, 0x94, 0x83, 0x2e, 0x53, 0x2c, 0x24,
	0xc4, 0xc5, 0x92, 0x9b, 0x5f, 0x94, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0x66, 0x27,
	0xb1, 0x81, 0x9d, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x11, 0x3c, 0xb9, 0x0d, 0xba, 0x00,
	0x00, 0x00,
}
